### ISSUE TITLE
Official Implementation

### ISSUE THREAD

**Issue by PlayeerOne** [kleag/external-knowledge-codegen#83]
Hello, 

I would like to know if this is the official implementation of the paper "Incorporating External Knowledge through Pre-training
for Natural Language to Code Generation", if not how does it relate to the official implementation ?

**Comment by kleag** [comment]
Hi, 
No, this is a clone of the original one done to update and upgrade it. 
We did not improve the results a lot, though. 
You can find the original repository by going to the root of this project and following the link after "cloned from".

**Comment by PlayeerOne** [comment]
Thank you for the fast response. I found out about this project by researching a Java ASDL grammar text file. I found a simplified one in this project, could you by any chance point me to a complete Java ASDL grammar text file ?

**Comment by kleag** [comment]
I cannot point you to another grammar, but even if it is called simplified, this one was able to parse completely a large corpus of Java code.

**Comment by PlayeerOne** [comment]
> I cannot point you to another grammar, but even if it is called simplified, this one was able to parse completely a large corpus of Java code.

That's great to hear ! In any case, I am grateful I came across it. I believe it is the only Java asdl grammar available in all of Github.

**Comment by PlayeerOne** [comment]
> I cannot point you to another grammar, but even if it is called simplified, this one was able to parse completely a large corpus of Java code.

I have a couple of questions (I promise they might be my last ):
- **Citation:** I’m currently drafting a research article and would like to reference this grammar and testing approach accurately. Could you advise on your preferred citation format?

- **Test File Selection:** I’m interested in understanding the methodology used to choose the test files for validating the ASDL grammar. Could you provide insight into how these files were selected? For example, were they based on common Java constructs, edge cases, or specific language features?

Thank you in advance!
